apiVersion: v1
kind: ConfigMap
metadata:
  name: base-images-info-configmap
  namespace: tekton-ci
data:
  latest.json: |
    {
      "alpine": {
        "major": "3.18",
        "latest": "3.18.4",
        "registry": "docker.io",
        "repo": "alpine",
        "tag": "3.18.4",
        "os": "linux",
        "arch": "amd64",
        "digest": "0"
      },
      "ruby": {
        "major": "3.2",
        "latest": "3.2.2",
        "registry": "docker.io",
        "repo": "ruby",
        "tag": "3.2.2-alpine3.18",
        "version_tag": "3.2.2",
        "platform_tag": "alpine3.18",
        "os": "linux",
        "arch": "amd64",
        "digest": "0"
      },
      "azure-cli": {
        "major": "2.53",
        "latest": "2.53.1",
        "registry": "docker.io",
        "repo": "mcr.microsoft.com/azure-cli",
        "tag": "2.49.0",
        "os": "linux",
        "arch": "amd64",
        "digest": "0"
      }
    }
