apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: init-github-workspace
  namespace: tekton-ci
spec:
  workspaces:
    - name: source
      description: A workspace that contains github project
    # - name: ssh-directory
    #   description: |
    #     A workspace that contains .ssh diretory with private key, known_hosts, config, etc.
    #     These will be copied to the user's home before any git commands are run.
    #   optional: true
  params:
    - name: image
      description: Git CLI image to run the task
      type: string
      default: quay.io/metasync/git-cli:2.40.1-rel.0
    - name: verbose
      description: Log the commands that are executed
      type: string
      default: "false"
  stepTemplate:
    envFrom:
      - configMapRef:
          name: git-configmap
    env:
      - name: VERBOSE
        value: $(params.verbose)
  steps:
    - name: init-workspace
      image: $(params.image)
      script: |
        #!/bin/sh

        if [ "${VERBOSE}" = "true" ] ; then
          set -x
        fi

        # Set up git config
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"
        git config --global init.defaultBranch main
        git config --global credential.helper store
        [ "${GIT_SSL_VERIFY}" = false ] && git --global config http.sslVerify false
        [ "${GIT_SSL_CA_INFO}" = "" ] || git config --global http.sslCAInfo ${GIT_SSL_CA_INFO}
        echo "GitHub workspace is initialized successfully."
