apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: deployment-restart-trigger
  namespace: tekton-ci
spec:
  interceptors:
    - ref: 
        name: "cel"
      params:
        - name: "filter"
          value: header.match('X-TektonCI-Event', 'deployment-restart')
  bindings:
    - name: deployment
      value: $(body.deployment)
    - name: namespace
      value: $(body.namespace)
  template:
    ref: deployment-restart-trigger-template
