apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: deployment-restart-trigger-template
  namespace: tekton-ci
spec:
  params:
    - name: deployment
      description: Name of the Deployment to restart
    - name: namespace
      description: Namespace of the Deployment
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: deployment-restart-pipelinerun-
        namespace: tekton-ci
      spec:
        serviceAccountName: tekton-ci-sa
        pipelineRef:
          name: deployment-restart-pipeline
        params:
          - name: deployment
            value: "$(tt.params.deployment)"
          - name: namespace
            value: "$(tt.params.namespace)"
            