apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: gitops-repo-trigger-template
  namespace: tekton-ci
spec:
  params:
    - name: project
      description: GitOps project
    - name: app
      description: GitOps application
    - name: env
      description: GitOps environment (dev, qa, prd, etc)
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: gitops-repo-pipelinerun-
        namespace: tekton-ci
      spec:
        serviceAccountName: tekton-ci-sa
        pipelineRef:
          name: gitops-repo-pipeline
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi
          # - name: azure-ssh-credentials
          #   secret:
          #     secretName: azure-ssh-credentials
        params:
          - name: project
            value: $(tt.params.project)
          - name: app
            value: $(tt.params.app)
          - name: env
            value: $(tt.params.env)
