apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quay-image-check-trigger-template
  namespace: tekton-ci
spec:
  params:
    - name: repo
      description: Quay image repository url
    - name: org
      description: Quay organization where the image repository belongs to
    - name: check-only
      description: |
        If true, related fix actions will be trigggered accordingly.
        Default is "false".
      default: "false"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: quay-image-check-updates-pipelinerun-
        namespace: tekton-ci
      spec:
        serviceAccountName: tekton-ci-sa
        pipelineRef:
          name: quay-image-check-updates-pipeline
        workspaces:
          - name: base-images-info
            configmap:
              name: base-images-info-configmap 
        params:
          - name: repo
            value: $(tt.params.repo)
          - name: org
            value: $(tt.params.org)
          - name: check-only
            value: $(tt.params.check-only)
