apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quay-repo-trigger-template
  namespace: tekton-ci
spec:
  params:
    - name: project
      description: Quay project for GitOps
    - name: app
      description: Quay application for GitOps
    - name: org
      description: Quay organization for GitOps
    - name: visibility
      description: Visibility which the repository will start with
      default: private
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: quay-repo-pipelinerun-
        namespace: tekton-ci
      spec:
        serviceAccountName: tekton-ci-sa
        pipelineRef:
          name: quay-repo-pipeline
        params:
          - name: project
            value: $(tt.params.project)
          - name: app
            value: $(tt.params.app)
          - name: org
            value: $(tt.params.org)
          - name: visibility
            value: $(tt.params.visibility)
