apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quay-image-check-updates-pipeline
  namespace: tekton-ci
spec:
  description: |
    This pipeline check if the latest image in a given image repo
    is built with the latest base image. If not, it triggers image rebuild.
  params:
    - name: repo
      type: string
    - name: org
      type: string
    - name: check-only
      type: string
  workspaces:
    - name: base-images-info
  tasks:
    - name: check-base-image-updates
      taskRef:
        name: check-quay-image-on-base-image-updates
      workspaces:
        - name: base-images
          workspace: base-images-info
      params:
        - name: repo
          value: $(params.repo)
        - name: org
          value: $(params.org)
    - name: trigger-image-rebuild
      runAfter: ["check-base-image-updates"]
      when:
        - input: $(params.check-only)
          operator: in
          values: ["false"]
        - input: $(tasks.check-base-image-updates.results.updates-available)
          operator: in
          values: ["true"]
      taskRef: 
        name: trigger-quay-image-rebuild
      params:
        - name: repo
          value: $(params.repo)
        - name: org
          value: $(params.org)
