apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-tekton-ci-role-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: tekton-ci-sa
    namespace: tekton-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-tekton-ci-role
