apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ci-sa-eventlistener-binding
  namespace: tekton-ci
subjects:
  - kind: ServiceAccount
    name: tekton-ci-sa
    namespace: tekton-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ci-sa-tekton-binding
  namespace: tekton-ci
subjects:
  - kind: ServiceAccount
    name: tekton-ci-sa
    namespace: tekton-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-tekton-ci-role
