apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-ci-clusterrole
rules:
  # The following permissions are needed for K8S namespace creation
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: ["list", "create"]
  # The following permissions are needed for K8S deployment rollout restart
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  # The following permissions are needed for OpenShift project creation
  # - apiGroups: ["project.openshift.io"]
  #   resources: ["projectrequests"]
  #   verbs: ["create"]
  - apiGroups: [""] 
    resources: ["secrets"]
    verbs: ["list", "get", "create", "patch"]
  - apiGroups: ["kpack.io"]
    resources: ["images"]
    verbs: ["get", "patch"]
  