apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-ci-clusterrole
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: ["list", "create"]
  - apiGroups: [""] 
    resources: ["secrets"]
    verbs: ["list", "get", "create", "patch"]