apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-tekton-ci-role
  namespace: tekton-ci
rules:
  - apiGroups: ["tekton.dev"] 
    resources: ["pipelineruns"]
    verbs: ["list", "get", "watch"]