PROJECT_NAME := gitops-tasks
APP_NAME := gitops-cli
APP_VERSION := 0.1.0
APP_REVISION := $(shell git log --pretty=format:'%h' -n 1)
APP_SOURCE := $(shell git config --get remote.origin.url)
APP_CONTEXT := docker/gitops-cli
APP_DOCKERFILE := Dockerfile

IMAGE_REPO := quay.io/metasync/${APP_NAME}
IMAGE_TAG := ${APP_VERSION}-rel.1
IMAGE_NAME := ${IMAGE_REPO}:${IMAGE_TAG}

BASE_IMAGE_REPO := alpine
BASE_IMAGE_TAG := 3.18.0

GITOPS_HOME := /home/gitops

CONTAINER_CLI := docker
# CONTAINER_CLI := podman
