PROJECT_NAME := gitops-tasks
APP_NAME := gitops-cli
APP_VERSION := 0.1.4
APP_REVISION := $(shell git log --pretty=format:'%h' -n 1)
APP_SOURCE := $(shell git config --get remote.origin.url)
APP_CONTEXT := docker/gitops-cli
APP_DOCKERFILE := Dockerfile

IMAGE_REPO := quay.io/metasync/${APP_NAME}
IMAGE_TAG := ${APP_VERSION}
IMAGE_NAME := ${IMAGE_REPO}:${IMAGE_TAG}

RELEASE_TAG := rel
BUILD_NUMBER := 0
IMAGE_REGISTRY_NAME := ${IMAGE_REPO}:${IMAGE_TAG}-${RELEASE_TAG}.${BUILD_NUMBER}

BASE_IMAGE_REPO := alpine
BASE_IMAGE_TAG := 3.21.0
BASE_IMAGE_DIGEST := sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45

GITOPS_HOME := /home/gitops

CONTAINER_CLI := docker
# CONTAINER_CLI := podman
